# 1. ĐỔI MODEL SANG QWEN (Hỗ trợ Tiếng Việt tốt nhất hiện nay cho dòng 7B)
model: "mlx-community/Qwen2.5-7B-Instruct-4bit"

train: true
data: "data"

# 2. CẤU HÌNH CHO MÁY 16GB RAM
lora_layers: 8
batch_size: 1        # Giữ nguyên 1 để không tràn RAM
grad_checkpoint: true # Bắt buộc bật
iters: 600
learning_rate: 1e-4
steps_per_eval: 100
save_every: 100
adapter_path: "adapters"
max_seq_length: 1024