model: "mlx-community/Qwen2.5-7B-Instruct-4bit"
train: true
data: "data"

learning_rate: 1e-5  # Giữ nguyên mức thấp này
iters: 200           # <--- GIẢM CÁI NÀY (Cũ là 600 -> Quá nhiều)

lora_layers: 8
batch_size: 1
grad_checkpoint: true
steps_per_eval: 50   # Giảm cái này xuống để nó log thường xuyên hơn
save_every: 50
adapter_path: "adapters"
max_seq_length: 1024