# Cấu hình cho Qwen 2.5 1.5B
model: "Qwen/Qwen2.5-1.5B-Instruct"  # <--- Đảm bảo đúng 1.5B
train: true
data: "data/"

lora_layers: 8
lora_parameters:
  rank: 8
  scale: 16.0 # Giảm scale một chút cho ổn định hơn
  dropout: 0.0

learning_rate: 1e-5                 # <--- Tốc độ cực chậm (Anti-NaN)
iters: 200                          # <--- Học ít thôi (Anti-overfitting)
batch_size: 1
max_seq_length: 1024